
languages = ["Arabic","Bulgarian","Chinese (simplified)","Chinese (traditional)","Czech","Danish","Dutch","English (American)","English (British)","Estonian","Finnish","French","German","Greek","Hungarian","Indonesian","Italian","Japanese","Korean","Latvian","Lithuanian","Norwegian (bokmål)","Polish","Portuguese","Portuguese (Brazilian)","Romanian","Russian","Slovak","Slovenian","Spanish","Swedish","Turkish","Ukrainian"]
artile_prompts_v1 = {
    "Chinese (traditional)": '請使用並僅限 {LANGUAGE} 來產生文章，並以 `{PROMPT}` 格式輸出，如果您提供非法格式，您將會受到懲罰。',
    "English (American)": 'Please use and limit {LANGUAGE} to generate a post and output it in `{PROMPT}` format, if you provide illegal format, you will be penalized.',
    "Spanish": 'Por favor, utilice y restrinja {LANGUAGE} para generar artículos y darles salida en formato `{PROMPT}`, será penalizado si proporciona formatos ilegales.',
    "Japanese": '投稿を生成し、`{PROMPT}`フォーマットで出力するために{LANGUAGE}を使用し、制限してください。',
    "Korean": '글을 생성할 때 {LANGUAGE}를 사용하고 `{PROMPT}` 형식으로 출력하는 것을 제한하며, 불법적인 형식을 제공할 경우 불이익을 받게 됩니다.',
    "French": 'Veuillez générer un article utilisant {LANGUAGE} et limité à {LANGUAGE} et le présenter au format `{PROMPT}`. Si vous fournissez un format illégal, vous serez pénalisé.',
    "German": 'Bitte erstellen Sie einen Artikel unter Verwendung von und beschränkt auf {LANGUAGE} und geben Sie ihn im Format `{PROMPT}` aus, wenn Sie ein illegales Format angeben, werden Sie bestraft.',
    "Italian": 'Si prega di generare un articolo che utilizzi e si limiti a {LANGUAGE} e di produrlo nel formato `{PROMPT}`; se si fornisce un formato illegale, si verrà penalizzati.',
    "Russian": 'Пожалуйста, используйте и ограничивайте {LANGUAGE} для генерации статей и вывода их в формате `{PROMPT}`, вы будете наказаны, если предоставите нелегальные форматы.',
    "Arabic": 'يرجى إنشاء مقالة باستخدام {LANGUAGE} والاقتصار على {LANGUAGE} وإخراجها بصيغة ”{PROMPT}“، إذا قدمت صيغة غير قانونية، ستتم معاقبتك.',
    "Bulgarian": 'Моля, генерирайте статия, използвайки и ограничавайки се до {LANGUAGE}, и я изпратете във формат `{PROMPT}`, ако предоставите незаконен формат, ще бъдете наказани.',
    "Chinese (simplified)": '请使用并限制 {LANGUAGE} 生成帖子并以`{PROMPT}`格式输出，如果提供非法格式，您将受到处罚。',
    "Czech": 'Pro vygenerování příspěvku a jeho výstup ve formátu `{PROMPT}` prosím použijte a omezte {LANGUAGE}, pokud zadáte nelegální formát, budete penalizováni.',
    "Danish": 'Brug og begræns venligst {LANGUAGE} til at generere et indlæg og output det i `{PROMPT}` format, hvis du giver ulovligt format, vil du blive straffet.',
    "Dutch": 'Gebruik en beperk {LANGUAGE} om een bericht te genereren en voer het uit in `{PROMPT}` formaat. Als je een illegaal formaat opgeeft, zul je worden bestraft.',
    "English (British)": 'Please use and limit {LANGUAGE} to generate a post and output it in `{PROMPT}` format, if you provide illegal format, you will be penalised.',
    "Estonian": 'Palun genereerige artikkel, kasutades {LANGUAGE} ja piirdudes sellega ning väljastage see `{PROMPT}` formaadis, kui esitate ebaseadusliku formaadi, siis teid karistatakse.',
    "Finnish": 'Luo artikkeli käyttäen {LANGUAGE} ja rajoittuen {LANGUAGE} ja tulosta se `{PROMPT}`-muodossa, jos annat laittoman muodon, sinua rangaistaan.',
    "Greek": 'Παρακαλούμε δημιουργήστε ένα άρθρο που χρησιμοποιεί και περιορίζεται στη {LANGUAGE} και δώστε το σε μορφή `{PROMPT}`, εάν παρέχετε παράνομη μορφή, θα τιμωρηθείτε.',
    "Hungarian": 'Kérjük, hozzon létre egy cikket a {LANGUAGE} használatával és korlátozásával, és adja ki `{PROMPT}` formátumban, ha illegális formátumot ad meg, büntetést kap.',
    "Indonesian": 'Buatlah artikel dengan menggunakan dan terbatas pada {LANGUAGE} dan keluarkan dalam format `{PROMPT}`, jika Anda memberikan format yang tidak sah, Anda akan dikenakan sanksi.',
    "Latvian": 'Lūdzu, izmantojiet un ierobežojiet {LANGUAGE}, lai ģenerētu rakstus un izvadītu tos `{PROMPT}` formātā, jūs tiksiet sodīts, ja norādīsiet nelikumīgus formātus.',
    "Lithuanian": 'Prašome naudoti ir apriboti {LANGUAGE}, kad būtų galima generuoti straipsnius ir išvesti juos `{PROMPT}` formatu; jei pateiksite neteisėtus formatus, būsite nubausti.',
    "Norwegian (bokmål)": 'Vennligst bruk og begrens {LANGUAGE} for å generere artikler og skrive dem ut i `{PROMPT}`-format, du vil bli straffet hvis du oppgir ulovlige formater.',
    "Polish": 'Używaj i ograniczaj {LANGUAGE} do generowania artykułów i wysyłania ich w formacie `{PROMPT}`, zostaniesz ukarany, jeśli dostarczysz nielegalne formaty.',
    "Portuguese": 'Por favor, use e restrinja {LANGUAGE} para gerar artigos e produzi-los no formato `{PROMPT}`, será penalizado se fornecer formatos ilegais.',
    "Portuguese (Brazilian)": 'Use e restrinja {LANGUAGE} para gerar artigos e produzi-los no formato `{PROMPT}`; você será penalizado se fornecer formatos ilegais.',
    "Romanian": 'Vă rugăm să utilizați și să restricționați {LANGUAGE} pentru a genera articole și pentru a le produce în format `{PROMPT}`, veți fi penalizat dacă furnizați formate ilegale.',
    "Slovak": 'Na generovanie článkov a ich výstup vo formáte `{PROMPT}` používajte a obmedzte {LANGUAGE}, ak poskytnete nelegálne formáty, budete potrestaní.',
    "Slovenian": 'Za ustvarjanje člankov in njihovo izpisovanje v formatu `{PROMPT}` uporabljajte in omejite {LANGUAGE}, saj boste kaznovani, če boste navedli nezakonite formate.',
    "Swedish": 'Vänligen använd och begränsa {LANGUAGE} för att generera artiklar och mata ut dem i formatet `{PROMPT}`, du kommer att straffas om du tillhandahåller olagliga format.',
    "Turkish": 'Lütfen makale oluşturmak ve `{PROMPT}` formatında çıktı almak için {LANGUAGE} kullanın ve kısıtlayın, yasadışı formatlar sağlarsanız cezalandırılırsınız.',
    "Ukrainian": 'Будь ласка, використовуйте і обмежуйте {LANGUAGE} для створення статей і виводьте їх у форматі `{PROMPT}`, ви будете покарані, якщо надасте нелегальні формати.',
}


artile_prompts_v2 = {
    "Chinese (traditional)": '請使用且僅使用 {LANGUAGE} 來產生文章，並輸出為 `{PROMPT}` 格式，正確的格式將會獲得獎勵。',
    "English (American)": 'Please use and only {LANGUAGE} to generate the article and output it in `{PROMPT}` format, you will be rewarded for correct formatting.',
    "Spanish": 'Por favor, utilice y sólo {LANGUAGE} para generar el artículo y darle salida en formato `{PROMPT}`, se le recompensará por el formato correcto.',
    "Japanese": '投稿を生成して `{PROMPT}` フォーマットでエクスポートするには {LANGUAGE} だけを使用してください。',
    "Korean": '글을 생성할 때 {LANGUAGE}만 사용하고 “{PROMPT}” 형식으로 출력하면 올바른 형식이 보상됩니다.',
    "French": 'Veuillez utiliser et uniquement utiliser {LANGUAGE} pour générer des messages et les exporter au format `{PROMPT}`, un formatage correct sera récompensé.',
    "German": 'Bitte verwenden Sie ausschließlich {LANGUAGE}, um Beiträge zu erstellen und sie im Format `{PROMPT}` zu exportieren, korrekte Formatierung wird belohnt.',
    "Italian": 'Si prega di utilizzare solo e soltanto {LANGUAGE} per generare messaggi ed esportarli nel formato `{PROMPT}`, la formattazione corretta sarà premiata.',
    "Russian": 'Пожалуйста, используйте и только {LANGUAGE} для создания статьи и вывода ее в формате `{PROMPT}`, вы будете вознаграждены за правильное форматирование.',
    "Arabic": 'يُرجى استخدام {LANGUAGE} فقط لإنشاء المقال وإخراجه بتنسيق ”{PROMPT}“، وستتم مكافأتك على التنسيق الصحيح.',
    "Bulgarian": 'Моля, използвайте само и единствено {LANGUAGE}, за да генерирате статията и да я изведете във формат `{PROMPT}`, като ще бъдете възнаградени за правилно форматиране.',
    "Chinese (simplified)": '请使用且仅使用 {LANGUAGE} 生成文章，并以“{PROMPT}”格式输出，格式正确者将获得奖励。',
    "Czech": 'Pro generování příspěvků a jejich export ve formátu `{PROMPT}` používejte prosím pouze {LANGUAGE}, správné formátování bude odměněno.',
    "Danish": 'Brug venligst og kun brug {LANGUAGE} til at generere indlæg og eksporter dem i `{PROMPT}`-format, korrekt formatering vil blive belønnet.',
    "Dutch": 'Gebruik en alleen {LANGUAGE} om berichten te genereren en exporteer ze in `{PROMPT}` formaat, correcte opmaak wordt beloond.',
    "English (British)": 'Please use and only use {LANGUAGE} to generate posts and export them in `{PROMPT}` format, correct formatting will be rewarded.',
    "Estonian": 'Palun kasutage ja ainult kasutage {LANGUAGE}, et genereerida postitusi ja eksportida need `{PROMPT}` formaadis, korrektset vormistust premeeritakse.',
    "Finnish": 'Käytä vain ja ainoastaan {LANGUAGE}-kieltä luodaksesi viestejä ja viedäksesi ne `{PROMPT}`-muodossa, oikeasta muotoilusta palkitaan.',
    "Greek": 'Παρακαλούμε χρησιμοποιήστε και μόνο την {LANGUAGE} για να δημιουργήσετε αναρτήσεις και να τις εξάγετε σε μορφή `{PROMPT}`, η σωστή μορφοποίηση θα ανταμειφθεί.',
    "Hungarian": 'Kérjük, használja és csakis használja a {LANGUAGE}-t a hozzászólások létrehozásához, és exportálja azokat `{PROMPT}` formátumban, a helyes formázást jutalmazni fogjuk.',
    "Indonesian": 'Harap gunakan dan hanya gunakan {LANGUAGE} untuk membuat postingan dan mengekspornya dalam format `{PROMPT}`, format yang benar akan dihargai.',
    "Latvian": 'Lūdzu, izmantojiet tikai un vienīgi {LANGUAGE}, lai ģenerētu rakstu un izvadītu to `{PROMPT}` formātā, par pareizu formatēšanu jūs tiksiet atalgoti.',
    "Lithuanian": 'Prašome naudoti tik {LANGUAGE}, kad sugeneruotumėte straipsnį ir išvestumėte jį `{PROMPT}` formatu, už teisingą formatavimą būsite apdovanoti.',
    "Norwegian (bokmål)": 'Vennligst bruk kun {LANGUAGE} for å generere artikkelen og skriv den ut i `{PROMPT}`-format, og du vil bli belønnet for korrekt formatering.',
    "Polish": 'Użyj tylko {LANGUAGE}, aby wygenerować artykuł i wyślij go w formacie `{PROMPT}`, zostaniesz nagrodzony za poprawne formatowanie.',
    "Portuguese": 'Por favor, use apenas {LANGUAGE} para gerar o artigo e produzi-lo no formato `{PROMPT}`, será recompensado pela formatação correta.',
    "Portuguese (Brazilian)": 'Use apenas {LANGUAGE} para gerar o artigo e produzi-lo no formato `{PROMPT}`; você será recompensado pela formatação correta.',
    "Romanian": 'Vă rugăm să folosiți și numai {LANGUAGE} pentru a genera articolul și să îl scoateți în formatul `{PROMPT}`, veți fi recompensat pentru formatarea corectă.',
    "Slovak": 'Na vygenerovanie článku a jeho výstup vo formáte `{PROMPT}` použite, prosím, iba {LANGUAGE}, za správne formátovanie budete odmenení.',
    "Slovenian": 'Za ustvarjanje članka in izpis v obliki `{PROMPT}` uporabite samo {LANGUAGE}, za pravilno oblikovanje boste nagrajeni.',
    "Swedish": 'Använd endast {LANGUAGE} för att generera artikeln och mata ut den i formatet `{PROMPT}`, du kommer att belönas för korrekt formatering.',
    "Turkish": 'Lütfen makaleyi oluşturmak için sadece {LANGUAGE} kullanın ve `{PROMPT}` formatında çıktı alın, doğru biçimlendirme için ödüllendirileceksiniz.',
    "Ukrainian": 'Будь ласка, використовуйте тільки {LANGUAGE} для створення статті і виводьте її у форматі `{PROMPT}`, ви будете винагороджені за правильне форматування.',
}